version: '3.1'

services:

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - dbdata6:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - my-network
      
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    depends_on:
      - mongo
    networks:
      - my-network
  
  backend:
    container_name: nest-backend
    image: node-app
    env_file:
      - .env
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      - mongo
    
    networks:
      - my-network

volumes:
  dbdata6:

networks:
  my-network:
    driver: bridge
